//
// Created by 72358 on 6/02/2025.
//

#ifndef DATA_ESTRUCTURE_C_DOUBLELINKEDLIST_H
#define DATA_ESTRUCTURE_C_DOUBLELINKEDLIST_H


class DoubleLinkedList {

};


#endif //DATA_ESTRUCTURE_C_DOUBLELINKEDLIST_H
